CREATE TABLE doctors (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `crm` VARCHAR(6) NOT NULL UNIQUE,
  `specialty` VARCHAR(100) NOT NULL,
  `public_area` VARCHAR(100) NOT NULL,
  `neighborhood` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `complement` VARCHAR(100) NULL,
  `number` VARCHAR(20) NULL,
  PRIMARY KEY (`id`));
)
